### ISSUE TITLE
Library crashes my app, I think it has many bugs or was not properly tested

### ISSUE THREAD

**Issue by oasisconsult** [raheemadamboev/pin-lock-compose#4]
FATAL EXCEPTION: main
Process: com.mine.app, PID: 22559
java.lang.NoSuchMethodError: No static method AnimatedContent(Ljava/lang/Object;Landroidx/compose/ui/Modifier;Lkotlin/jvm/functions/Function1;Landroidx/compose/ui/Alignment;Lkotlin/jvm/functions/Function4;Landroidx/compose/runtime/Composer;II)V in class Landroidx/compose/animation/AnimatedContentKt; or its super classes (declaration of 'androidx.compose.animation.AnimatedContentKt' appears in /data/app/~~fTGKh1WwePjJ8HhiO6mY1Q==/commine.app-2XTrsyZLKNXVlP2htZsubA==/base.apk)
	at xyz.teamgravity.pin_lock_compose.PinLockKt$BasePinLock-8V94_ZQ$$inlined$ConstraintLayout$2.invoke(ConstraintLayout.kt:1575)
	at xyz.teamgravity.pin_lock_compose.PinLockKt$BasePinLock-8V94_ZQ$$inlined$ConstraintLayout$2.invoke(ConstraintLayout.kt:89)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:108)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
	at androidx.compose.ui.layout.LayoutKt.MultiMeasureLayout(Layout.kt:443)
	at xyz.teamgravity.pin_lock_compose.PinLockKt.BasePinLock-8V94_ZQ(PinLock.kt:458)
	at xyz.teamgravity.pin_lock_compose.PinLockKt.PinLock-sW7UJKQ(PinLock.kt:53)
	at com.XXXX.XXXX.screen.XXX.Keypad(Keypad.kt:46)
	at com.appp.minw.navigation.ComposableSingletons$NavGraphKt$lambda-1$1.invoke(NavGraph.kt:36)
	at com.app.minw.navigation.ComposableSingletons$NavGraphKt$lambda-1$1.invoke(NavGraph.kt:35)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:117)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
	at androidx.navigation.compose.NavHostKt$NavHost$4$1.invoke(NavHost.kt:150)
	at androidx.navigation.compose.NavHostKt$NavHost$4$1.invoke(NavHost.kt:149)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:108)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
	at androidx.compose.runtime.saveable.SaveableStateHolderImpl.SaveableStateProvider(SaveableStateHolder.kt:84)
	at androidx.navigation.compose.NavBackStackEntryProviderKt.SaveableStateProvider(NavBackStackEntryProvider.kt:60)
	at androidx.navigation.compose.NavBackStackEntryProviderKt.access$SaveableStateProvider(NavBackStackEntryProvider.kt:1)
	at androidx.navigation.compose.NavBackStackEntryProviderKt$LocalOwnersProvider$1.invoke(NavBackStackEntryProvider.kt:52)
	at androidx.navigation.compose.NavBackStackEntryProviderKt$LocalOwnersProvider$1.invoke(NavBackStackEntryProvider.kt:51)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:108)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
	at androidx.navigation.compose.NavBackStackEntryProviderKt.LocalOwnersProvider(NavBackStackEntryProvider.kt:47)
	at androidx.navigation.compose.NavHostKt$NavHost$4.invoke(NavHost.kt:149)
	at androidx.navigation.compose.NavHostKt$NavHost$4.invoke(NavHost.kt:142)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:117)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
	at androidx.compose.animation.CrossfadeKt$Crossfade$5$1.invoke(Crossfade.kt:133)
	at androidx.compose.animation.CrossfadeKt$Crossfade$5$1.invoke(Crossfade.kt:128)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:108)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
	at androidx.compose.animation.CrossfadeKt.Crossfade(Crossfade.kt:142)
	at androidx.compose.animation.CrossfadeKt.Crossfade(Crossfade.kt:73)

**Comment by zaneschepke** [comment]
It doesn't look like this lib is getting supported anymore. I am maintaining  created a fork [here](https://github.com/zaneschepke/pin_lock_compose).

**Comment by raheemadamboev** [comment]
@oasisconsult I'm releasing new version with upgraded dependencies, please let me know if crash persists in new version of the library!
